### ISSUE TITLE
A to-do list before I even get to Brainhack

### ISSUE THREAD

**Issue by garner-code** [kel-github/PSY2R#31]
- [x] Project and Repo readme's are up to date - use project to orient people to tasks
- [x] Tidy up repo
- [x] Presentation/intro slide
- [x] Clear any old issues from repo that are not 
- [x] Break down the GCR implementation tasks into documented to-do lists
- [x] We need to compare between emmeans and MBESS to see which functions they have that overlap with PSY. reproduce and document using dummy data and contrasts
- [x] Check dummy data and contrasts
- [x] Need to understand better the way that emmeans interacts with model outputs to come up with outputs. Should we build on them, or can we use the code somehow? Document this to-do and workflow
- [x] Check Emily Nordmann's info on how to create an R package
- [x] Add a guide to analysing the example data in PSY
- [x] submit project to Brainhack!
- [ ] read Kevin's email
